"""nueva_fila_usuario

Revision ID: 860a381cc11a
Revises: d0aa9a074a8d
Create Date: 2026-05-08 19:46:14.704565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860a381cc11a'
down_revision: Union[str, Sequence[str], None] = 'd0aa9a074a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nombre')
    # ### end Alembic commands ###
