"""cambios_generales

Revision ID: d4a4bcb13982
Revises: 860a381cc11a
Create Date: 2026-05-13 21:55:37.336255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a4bcb13982'
down_revision: Union[str, Sequence[str], None] = '860a381cc11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('estado', sa.String(), nullable=True))
    op.drop_column('clientes', 'nombre_completo')
    op.add_column('control_accesos', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('detalles_venta', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('disciplinas', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('evaluaciones_biometricas', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('pagos', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('planes_suscripcion', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('productos_tienda', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('sesiones_programadas', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('tickets_mantenimiento', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('ventas_tienda', sa.Column('estado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas_tienda', 'estado')
    op.drop_column('usuarios', 'estado')
    op.drop_column('usuarios', 'nombre')
    op.drop_column('tickets_mantenimiento', 'estado')
    op.drop_column('sesiones_programadas', 'estado')
    op.drop_column('roles', 'estado')
    op.drop_column('productos_tienda', 'estado')
    op.drop_column('planes_suscripcion', 'estado')
    op.drop_column('pagos', 'estado')
    op.drop_column('evaluaciones_biometricas', 'estado')
    op.drop_column('entrenadores', 'estado')
    op.drop_column('disciplinas', 'estado')
    op.drop_column('detalles_venta', 'estado')
    op.drop_column('control_accesos', 'estado')
    op.add_column('clientes', sa.Column('nombre_completo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('clientes', 'estado')
    # ### end Alembic commands ###
