"""migracion_inicial_sqlite

Revision ID: f2548b823b1d
Revises: 
Create Date: 2026-05-18 22:43:19.722706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2548b823b1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos_tienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_maquina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquinas_categoria_id'), 'maquinas', ['categoria_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_rol_id'), 'usuarios', ['rol_id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('entrenadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('tickets_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_mantenimiento_maquina_id'), 'tickets_mantenimiento', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_tickets_mantenimiento_usuario_id'), 'tickets_mantenimiento', ['usuario_id'], unique=False)
    op.create_table('control_accesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_accesos_cliente_id'), 'control_accesos', ['cliente_id'], unique=False)
    op.create_table('evaluaciones_biometricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estatura', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('porcentaje_grasa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_biometricas_cliente_id'), 'evaluaciones_biometricas', ['cliente_id'], unique=False)
    op.create_table('membresias_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membresias_cliente_cliente_id'), 'membresias_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_membresias_cliente_plan_id'), 'membresias_cliente', ['plan_id'], unique=False)
    op.create_table('sesiones_programadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('cupo_maximo', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_programadas_disciplina_id'), 'sesiones_programadas', ['disciplina_id'], unique=False)
    op.create_index(op.f('ix_sesiones_programadas_entrenador_id'), 'sesiones_programadas', ['entrenador_id'], unique=False)
    op.create_table('ventas_tienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_tienda_cliente_id'), 'ventas_tienda', ['cliente_id'], unique=False)
    op.create_table('detalles_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_tienda.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_tienda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_venta_producto_id'), 'detalles_venta', ['producto_id'], unique=False)
    op.create_index(op.f('ix_detalles_venta_venta_id'), 'detalles_venta', ['venta_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=False),
    sa.Column('membresia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias_cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('sesion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_programadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_detalles_venta_venta_id'), table_name='detalles_venta')
    op.drop_index(op.f('ix_detalles_venta_producto_id'), table_name='detalles_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_ventas_tienda_cliente_id'), table_name='ventas_tienda')
    op.drop_table('ventas_tienda')
    op.drop_index(op.f('ix_sesiones_programadas_entrenador_id'), table_name='sesiones_programadas')
    op.drop_index(op.f('ix_sesiones_programadas_disciplina_id'), table_name='sesiones_programadas')
    op.drop_table('sesiones_programadas')
    op.drop_index(op.f('ix_membresias_cliente_plan_id'), table_name='membresias_cliente')
    op.drop_index(op.f('ix_membresias_cliente_cliente_id'), table_name='membresias_cliente')
    op.drop_table('membresias_cliente')
    op.drop_index(op.f('ix_evaluaciones_biometricas_cliente_id'), table_name='evaluaciones_biometricas')
    op.drop_table('evaluaciones_biometricas')
    op.drop_index(op.f('ix_control_accesos_cliente_id'), table_name='control_accesos')
    op.drop_table('control_accesos')
    op.drop_index(op.f('ix_tickets_mantenimiento_usuario_id'), table_name='tickets_mantenimiento')
    op.drop_index(op.f('ix_tickets_mantenimiento_maquina_id'), table_name='tickets_mantenimiento')
    op.drop_table('tickets_mantenimiento')
    op.drop_table('entrenadores')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_rol_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_maquinas_categoria_id'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_table('roles')
    op.drop_table('productos_tienda')
    op.drop_table('planes_suscripcion')
    op.drop_table('disciplinas')
    op.drop_table('categorias_maquina')
    # ### end Alembic commands ###
